language: generic

root: required

services:
  - docker

before_install:
  - docker build -t notsimpletext/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true notsimpletext/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-049110340081"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY